databases:
  - name: budget_app
    databaseName: budget_app_db
    user: budget_app_user
services:
  - type: web
    name: budget_app
    runtime: ruby
    buildCommand: './bin/render-build.sh'
    startCommand: 'bundle exec puma -C config/puma.rb'
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: budget_app_db
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
